# -*- coding: utf-8 -*-
"""image classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aU3e6Bu2lOmrWl_97YYeQc0e0WfVBdRG
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
# %matplotlib inline

data=pd.read_csv('mnist_test.csv.zip')

data.head()

start_index=1
end_index=start_index+784
a = data.iloc[4, start_index:end_index].values

a= a.reshape(28,28).astype('uint8')
plt.imshow(a)

x=data.iloc[:,1:]
y=data.iloc[:,0]

x_train ,x_test ,y_train ,y_test=train_test_split(x,y,test_size=0.2,random_state=4)

y_train.head()

rf=RandomForestClassifier(n_estimators=100)

rf.fit(x_train,y_train)

pred=rf.predict(x_test)

pred

s=y_test.values
count=0
for i in range(len(pred)):
  if pred[i]==s[i]:
    count+=1

count

len(pred)

j=1897/2000
j